sudo: false
language: elixir
git:
  depth: 3
elixir:
  - 1.7
otp_release:
  - 21.1.1
env:
  - MIX_ENV=test VERBOSE_TESTS=true
script:
  - mix test
notifications:
  slack:
    secure: qaHDF9PnpM2uTLKUlKGMvjV5Tz51w4wsGyFv11P9+hMvvFTjkn3yScuNfa9ubc/rdIAcXulAJF17qdicEW8blsQD4EOZOMLe+cJBMrpKnw8vuRuQM0Vx9nmYJLaYyHrWU36v+sBcmmEzJU96Q+4VWptp1pRpjXbVHW2lnsvWhW41UP/Vy5vAAWvLcM7sGJeMQ77eTGVxgIC5kH1PpZmslp+11H0DKBFQg2PIBIS0V0H3ujCDst8XWQf+pWyNt80otpDbVYpknX+Nzge3TfM/eAngP4ADZhZHE1BB3MZVUlULo8FyZvg5A62sa9ynA6mbnjd8PyInnEMAQVYVewXz9sbi0HXoOZGxIKJFWFQoyNm3gxd1mHknzDcEBzA4aaPm/G5ffNT9qdcyNSMXQ+1W3KEA9YLaEMjMmnQVjqt+SoWO/XXDJuw1Ksdv92j8raOa/KdbGBa81Kb5pY6SHncRLggye+8JZ5ZxETDTrnb6tMT9ZdCpvILgTjVYF1KRsbxu2g5i6w5aL5iJt+UN3mi0Pkkf99S7a9ZRe4f1kVnnTWgNbE+dm97o9gtNtbeEqU8aiCKVv3Wc5WhlylaP85DpE9jB5KWHoJk0DRdBGZ58EfWRaFWS+Hbk57diqmTroCI52mW3xtpfU52YUIVw3JHUTYBwX5l7KqT+qH0h38IWb34=
