[agent]
  interval = "1m"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000

  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"

  precision = ""
  debug = false
  quiet = true
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "halosir"

  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"

[[inputs.filestat]]
  files = ["../../data/youdao.dets", "../../data/webster.dets"]
  md5 = false
